# Generated by Django 2.2.2 on 2019-06-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='')),
                ('resize_image', models.ImageField(default=None, null=True, upload_to='')),
                ('meta', models.TextField(default=None, null=True)),
            ],
        ),
    ]
