# Generated by Django 2.2.2 on 2019-06-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='meta',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='resize_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
