# Generated by Django 2.2.2 on 2019-06-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190626_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='original_image',
            field=models.ImageField(upload_to='original'),
        ),
        migrations.AlterField(
            model_name='image',
            name='resize_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='processed'),
        ),
    ]
